apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 4al2-groupe-2
  name: deployment-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: python:3.10.8-alpine3.16
