apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 4al2-groupe-2
  name: deployment-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: barlords/backend:latest
          env:
            - name: DATABASE_HOST
              value: database-service
            - name: DATABASE_NAME
              value: local_database
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_USER
              value: local_user
            - name: DATABASE_PASSWORD
              value: local_password

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000